export type Availability = "dine-in" | "takeout" | "both"

export type MenuCategory =
  | "Starters"
  | "Salads"
  | "Royal Platters"
  | "Festive Chicken"
  | "Shawarma"
  | "Western Destinations"
  | "Eastern Destinations"
  | "Curries"
  | "Biryani"
  | "Kababs"
  | "Pasta"
  | "Pizza"
  | "Coffee & Tea"
  | "Froyo & Desserts"
  | "Drinks"

export type MenuItem = {
  slug: string
  name: string
  category: MenuCategory
  price: number
  description: string
  availability: Availability
  pairings?: string[] // slugs
  imageQuery: string
}

const img = (q: string) => q

export const MENU: MenuItem[] = [
  // STARTERS
  {
    slug: "three_cheese_samosas",
    name: "Three-Cheese Samosas",
    category: "Starters",
    price: 199,
    description: "Golden flaky pockets filled with three cheeses, served with tangy chutney.",
    availability: "both",
    pairings: ["chicken_biryani", "butter_chicken_masala", "italian_soda"],
    imageQuery: img("golden crispy three cheese samosas with chutney on rustic plate, soft natural light, premium food photography"),
  },
  {
    slug: "hummus",
    name: "Hummus",
    category: "Starters",
    price: 179,
    description: "Creamy chickpea dip served with warm flat bread.",
    availability: "both",
    pairings: ["mixed_shish", "butter_chicken_masala"],
    imageQuery: img("creamy hummus bowl with olive oil drizzle and warm pita flat bread, cream linen background, premium minimal food photography"),
  },
  {
    slug: "cajun_fries",
    name: "Cajun Fries",
    category: "Starters",
    price: 179,
    description: "Crispy fries tossed in Cajun spices.",
    availability: "both",
    pairings: ["margherita_originale", "shawarma_rice"],
    imageQuery: img("crispy cajun seasoned fries on a stoneware plate, warm light, premium food photography"),
  },
  {
    slug: "persian_nachos",
    name: "Persian Nachos",
    category: "Starters",
    price: 299,
    description: "Persian-inspired loaded nachos with seasoned beef, sauce, and cheese.",
    availability: "both",
    pairings: ["cocktails", "italian_soda"],
    imageQuery: img("loaded persian style nachos with seasoned beef cheese sauce on dark plate, warm restaurant lighting"),
  },
  {
    slug: "shakshuka",
    name: "Shakshuka",
    category: "Starters",
    price: 199,
    description: "Eggs poached in tomato and pepper sauce, served with flat bread.",
    availability: "dine-in",
    pairings: ["hummus", "caffe_latte"],
    imageQuery: img("middle eastern shakshuka in cast iron pan with poached eggs tomato pepper sauce and flatbread, overhead view, premium food photography"),
  },

  // SALADS
  {
    slug: "caesar_salad",
    name: "Caesar Salad",
    category: "Salads",
    price: 220,
    description: "Crisp romaine, creamy Caesar dressing, croutons, and parmesan.",
    availability: "both",
    imageQuery: img("classic caesar salad with romaine croutons parmesan in white bowl, soft daylight, premium food photography"),
  },
  {
    slug: "kani_salad",
    name: "Kani Salad",
    category: "Salads",
    price: 220,
    description: "Crab sticks, vegetables, and creamy dressing.",
    availability: "both",
    imageQuery: img("japanese kani salad with crab sticks cucumber and creamy dressing in white bowl, premium food photography"),
  },
  {
    slug: "chefs_salad",
    name: "Chef's Salad",
    category: "Salads",
    price: 249,
    description: "Mixed vegetables with premium toppings and house dressing.",
    availability: "both",
    imageQuery: img("chefs salad with mixed greens egg ham cheese and tomatoes in ceramic bowl, premium food photography"),
  },
  {
    slug: "caprese_salad",
    name: "Caprese Salad",
    category: "Salads",
    price: 299,
    description: "Mozzarella, tomatoes, basil, and olive oil.",
    availability: "dine-in",
    imageQuery: img("italian caprese salad with fresh mozzarella tomato basil and olive oil on white plate, premium food photography"),
  },

  // ROYAL PLATTERS
  {
    slug: "soltani_platter",
    name: "Soltani Platter",
    category: "Royal Platters",
    price: 999,
    description: "Assorted kababs with rice and sides, ideal for sharing.",
    availability: "dine-in",
    pairings: ["cocktails", "frozen_yogurt"],
    imageQuery: img("persian soltani platter with assorted kababs basmati rice grilled tomatoes on wooden board, premium restaurant photography"),
  },
  {
    slug: "dynasty_platter",
    name: "Dynasty Platter",
    category: "Royal Platters",
    price: 999,
    description: "A group platter with curry, hummus, flat bread, grilled meats, and rice.",
    availability: "dine-in",
    pairings: ["italian_soda", "caffe_latte"],
    imageQuery: img("middle eastern dynasty sharing platter with curry hummus flatbread grilled meats and rice on wooden board, premium photography"),
  },
  {
    slug: "empire_platter",
    name: "Empire Platter",
    category: "Royal Platters",
    price: 2499,
    description: "A grand signature platter with curries, kababs, biryani rice, pita chips, and more.",
    availability: "dine-in",
    pairings: ["cocktails", "dubai_chocolate_kunafa"],
    imageQuery: img("grand empire feast platter with curries kababs biryani rice pita chips on large wooden board, overhead, premium restaurant photography"),
  },

  // FESTIVE CHICKEN
  {
    slug: "pollo_a_la_brasa",
    name: "Pollo a la Brasa",
    category: "Festive Chicken",
    price: 249,
    description: "Peruvian-inspired chicken served with rice and bold spices.",
    availability: "both",
    imageQuery: img("peruvian pollo a la brasa roasted chicken with rice on plate, premium food photography warm lighting"),
  },
  {
    slug: "fried_tandoori_chicken",
    name: "Fried Tandoori Chicken",
    category: "Festive Chicken",
    price: 199,
    description: "Indian-inspired marinated chicken fried until crispy.",
    availability: "both",
    imageQuery: img("crispy fried tandoori chicken with red marinade on stoneware plate, premium food photography"),
  },

  // SHAWARMA
  {
    slug: "shawarma_wrap_overload",
    name: "Shawarma Wrap Overload",
    category: "Shawarma",
    price: 199,
    description: "Beef or chicken wrapped in flat bread with vegetables, fries, and sauce.",
    availability: "both",
    pairings: ["italian_soda", "cajun_fries"],
    imageQuery: img("loaded shawarma wrap with beef vegetables fries and sauce halved on parchment, premium food photography"),
  },
  {
    slug: "shawarma_rice",
    name: "Shawarma Rice",
    category: "Shawarma",
    price: 199,
    description: "Beef or chicken served over golden basmati rice with rich sauce.",
    availability: "both",
    pairings: ["shawarma_fries", "italian_soda"],
    imageQuery: img("shawarma rice bowl with beef chicken over basmati rice with sauce, premium food photography"),
  },
  {
    slug: "shawarma_fries",
    name: "Shawarma Fries",
    category: "Shawarma",
    price: 249,
    description: "Crispy fries topped with shawarma meat, sauce, and cheese.",
    availability: "both",
    pairings: ["shawarma_rice", "italian_soda"],
    imageQuery: img("loaded shawarma fries topped with shawarma meat cheese and sauce on plate, premium food photography"),
  },
  {
    slug: "baked_shawarma",
    name: "Baked Shawarma",
    category: "Shawarma",
    price: 749,
    description: "Layered baked shawarma tray with cheese and flavorful toppings.",
    availability: "both",
    imageQuery: img("baked shawarma tray with melted cheese layered meat and herbs in casserole dish, premium food photography"),
  },

  // WESTERN DESTINATIONS
  {
    slug: "souvlaki_gyros",
    name: "Greece Souvlaki Gyros",
    category: "Western Destinations",
    price: 249,
    description: "Greek-inspired grilled meat wrap with tomatoes, onions, and sauce.",
    availability: "both",
    imageQuery: img("greek souvlaki gyros wrap with grilled meat tomatoes onions and tzatziki, premium food photography"),
  },
  {
    slug: "quesa_birria",
    name: "Mexico Quesa-Birria",
    category: "Western Destinations",
    price: 299,
    description: "Cheesy birria-style tacos with rich dipping sauce.",
    availability: "both",
    imageQuery: img("mexican quesabirria tacos with cheese pull and consome dipping sauce on dark plate, premium food photography"),
  },
  {
    slug: "chicken_fajitas",
    name: "Mexico Chicken Fajitas",
    category: "Western Destinations",
    price: 249,
    description: "Mexican-inspired chicken strips with vegetables and wrap.",
    availability: "both",
    imageQuery: img("mexican chicken fajitas sizzling on cast iron with peppers and tortillas, premium food photography"),
  },
  {
    slug: "baked_poutine",
    name: "Canada Baked Poutine",
    category: "Western Destinations",
    price: 299,
    description: "Fries baked with cheese and rich gravy.",
    availability: "dine-in",
    imageQuery: img("canadian baked poutine fries with cheese curds and gravy in cast iron skillet, premium food photography"),
  },

  // EASTERN DESTINATIONS
  {
    slug: "japan_katsu_curry",
    name: "Japan Katsu Curry",
    category: "Eastern Destinations",
    price: 220,
    description: "Crispy breaded cutlet with Japanese curry and rice.",
    availability: "both",
    imageQuery: img("japanese katsu curry with crispy breaded cutlet rice and curry sauce on plate, premium food photography"),
  },
  {
    slug: "beef_rendang",
    name: "Malaysia Beef Rendang",
    category: "Eastern Destinations",
    price: 220,
    description: "Tender beef simmered in rich Malaysian-style curry.",
    availability: "both",
    imageQuery: img("malaysian beef rendang tender beef in dark coconut curry with rice on plate, premium food photography"),
  },
  {
    slug: "beef_pho",
    name: "Vietnam Beef Pho",
    category: "Eastern Destinations",
    price: 249,
    description: "Beef noodle soup with fragrant broth.",
    availability: "dine-in",
    imageQuery: img("vietnamese beef pho noodle soup with herbs lime and beef in white bowl, overhead, premium food photography"),
  },
  {
    slug: "singapore_laksa",
    name: "Singapore Laksa",
    category: "Eastern Destinations",
    price: 249,
    description: "Spicy coconut curry noodle soup with Southeast Asian aromatics.",
    availability: "dine-in",
    imageQuery: img("singapore laksa spicy coconut curry noodle soup with prawns in bowl, premium food photography"),
  },
  {
    slug: "pad_thai",
    name: "Thailand Pad Thai",
    category: "Eastern Destinations",
    price: 249,
    description: "Stir-fried rice noodles with Thai-inspired flavor.",
    availability: "both",
    imageQuery: img("thai pad thai rice noodles with peanuts lime and prawns on plate, premium food photography"),
  },

  // CURRIES
  {
    slug: "chicken_curry",
    name: "Chicken Curry",
    category: "Curries",
    price: 220,
    description: "Aromatic curry with tender chicken in a rich sauce.",
    availability: "both",
    pairings: ["three_cheese_samosas", "caffe_latte"],
    imageQuery: img("indian chicken curry in copper bowl with cilantro and rice, premium food photography warm light"),
  },
  {
    slug: "beef_curry",
    name: "Beef Curry",
    category: "Curries",
    price: 220,
    description: "Tender beef simmered in Curry Empire's flavorful curry sauce.",
    availability: "both",
    imageQuery: img("indian beef curry in copper bowl with cilantro garnish and naan, premium food photography"),
  },
  {
    slug: "beef_keema",
    name: "Beef Keema",
    category: "Curries",
    price: 220,
    description: "Ground beef cooked with onions, garlic, tomatoes, and spices.",
    availability: "both",
    imageQuery: img("indian beef keema ground beef curry with peas in copper bowl, premium food photography"),
  },
  {
    slug: "pomapano_curry",
    name: "Pomapano Curry",
    category: "Curries",
    price: 299,
    description: "Fish curry with aromatic coconut curry sauce.",
    availability: "dine-in",
    imageQuery: img("pompano fish curry in coconut sauce in copper bowl with cilantro, premium food photography"),
  },
  {
    slug: "chicken_tikka_masala",
    name: "Chicken Tikka Masala",
    category: "Curries",
    price: 299,
    description: "Grilled chicken in a tomato-based curry sauce.",
    availability: "both",
    imageQuery: img("chicken tikka masala in copper bowl with rice and naan, creamy tomato curry, premium food photography"),
  },
  {
    slug: "butter_chicken_masala",
    name: "Butter Chicken Masala",
    category: "Curries",
    price: 299,
    description: "Creamy curry with tender chicken chunks in a smooth tomato sauce.",
    availability: "both",
    pairings: ["hummus", "caffe_latte"],
    imageQuery: img("butter chicken masala creamy tomato curry with chicken in copper bowl with naan, premium food photography"),
  },

  // BIRYANI
  {
    slug: "chicken_biryani",
    name: "Chicken Biryani",
    category: "Biryani",
    price: 249,
    description: "Aromatic biryani rice topped with flavorful chicken, spices, herbs, and house sauce.",
    availability: "both",
    pairings: ["three_cheese_samosas", "italian_soda"],
    imageQuery: img("aromatic chicken biryani rice with chicken pieces saffron and herbs in copper bowl, premium food photography overhead"),
  },
  {
    slug: "beef_biryani",
    name: "Beef Biryani",
    category: "Biryani",
    price: 249,
    description: "Aromatic biryani rice topped with tender beef and spices.",
    availability: "both",
    imageQuery: img("beef biryani aromatic rice with tender beef pieces and saffron in copper bowl, premium food photography"),
  },
  {
    slug: "beef_keema_biryani",
    name: "Beef Keema Biryani",
    category: "Biryani",
    price: 249,
    description: "Biryani rice served with seasoned beef keema.",
    availability: "both",
    imageQuery: img("beef keema biryani ground beef with aromatic rice and herbs in copper bowl, premium food photography"),
  },
  {
    slug: "pomapano_biryani",
    name: "Pomapano Biryani",
    category: "Biryani",
    price: 299,
    description: "Biryani rice paired with flavorful pomapano fish.",
    availability: "dine-in",
    imageQuery: img("pompano fish biryani aromatic rice with fish and herbs in copper bowl, premium food photography"),
  },
  {
    slug: "fried_chicken_biryani",
    name: "Fried Chicken Biryani",
    category: "Biryani",
    price: 249,
    description: "Crispy fried chicken served with aromatic biryani rice.",
    availability: "both",
    imageQuery: img("crispy fried chicken on aromatic biryani rice in copper bowl, premium food photography"),
  },
  {
    slug: "beef_kabab_biryani",
    name: "Beef Kabab Biryani",
    category: "Biryani",
    price: 249,
    description: "Beef kabab served over biryani rice.",
    availability: "both",
    imageQuery: img("beef kabab on aromatic biryani rice with herbs in copper bowl, premium food photography"),
  },
  {
    slug: "chicken_kabab_biryani",
    name: "Chicken Kabab Biryani",
    category: "Biryani",
    price: 249,
    description: "Chicken kabab served over biryani rice.",
    availability: "both",
    imageQuery: img("chicken kabab on aromatic biryani rice with herbs in copper bowl, premium food photography"),
  },

  // KABABS
  {
    slug: "beef_koobideh",
    name: "Beef Koobideh",
    category: "Kababs",
    price: 220,
    description: "Grilled ground beef kabab served with rice or flat bread.",
    availability: "both",
    imageQuery: img("persian beef koobideh kabab with saffron rice and grilled tomato on plate, premium food photography"),
  },
  {
    slug: "chicken_koobideh",
    name: "Chicken Koobideh",
    category: "Kababs",
    price: 220,
    description: "Grilled ground chicken kabab served with rice or flat bread.",
    availability: "both",
    imageQuery: img("persian chicken koobideh kabab with saffron rice and grilled tomato on plate, premium food photography"),
  },
  {
    slug: "mixed_shish",
    name: "Mixed Shish",
    category: "Kababs",
    price: 220,
    description: "Beef and chicken skewers grilled and served with rice or flat bread.",
    availability: "both",
    pairings: ["hummus", "italian_soda"],
    imageQuery: img("mixed shish kebab beef and chicken skewers with rice and flatbread, premium food photography"),
  },
  {
    slug: "kabab_burger",
    name: "Kabab Burger",
    category: "Kababs",
    price: 220,
    description: "Juicy kabab burger served with crispy fries.",
    availability: "both",
    imageQuery: img("kabab burger with juicy patty and fries on wooden board, premium food photography"),
  },
  {
    slug: "kabab_salisbury_steak",
    name: "Kabab Salisbury Steak",
    category: "Kababs",
    price: 299,
    description: "Fire-grilled kabab steak with rice, egg, and mushroom gravy.",
    availability: "dine-in",
    imageQuery: img("kabab salisbury steak with rice fried egg and mushroom gravy on plate, premium food photography"),
  },

  // PASTA
  {
    slug: "arrabbiata",
    name: "Arrabbiata",
    category: "Pasta",
    price: 199,
    description: "Spicy tomato pasta with Italian-inspired flavor.",
    availability: "both",
    imageQuery: img("italian arrabbiata pasta spicy tomato sauce with parsley in white bowl, premium food photography"),
  },
  {
    slug: "aglio_e_olio",
    name: "Aglio e Olio",
    category: "Pasta",
    price: 199,
    description: "Garlic and olive oil pasta with classic simple flavor.",
    availability: "both",
    imageQuery: img("italian aglio e olio pasta garlic olive oil parsley red pepper flakes in white bowl, premium food photography"),
  },
  {
    slug: "tartufo",
    name: "Tartufo",
    category: "Pasta",
    price: 199,
    description: "Creamy truffle-inspired pasta.",
    availability: "both",
    imageQuery: img("creamy truffle tartufo pasta in white bowl with shaved truffle and parmesan, premium food photography"),
  },
  {
    slug: "pesto",
    name: "Pesto",
    category: "Pasta",
    price: 199,
    description: "Basil pesto pasta with rich herb flavor.",
    availability: "both",
    imageQuery: img("italian basil pesto pasta with pine nuts and parmesan in white bowl, premium food photography"),
  },

  // PIZZA
  {
    slug: "margherita_originale",
    name: "Margherita Originale",
    category: "Pizza",
    price: 499,
    description: "Classic Margherita pizza with tomato, cheese, and basil.",
    availability: "both",
    pairings: ["cajun_fries", "italian_soda"],
    imageQuery: img("italian margherita pizza with fresh basil tomato and mozzarella on wooden board, premium food photography overhead"),
  },
  {
    slug: "salamino_picante",
    name: "Salamino Picante",
    category: "Pizza",
    price: 549,
    description: "Pepperoni pizza with a spicy kick.",
    availability: "both",
    imageQuery: img("italian pepperoni salamino picante pizza on wooden board, premium food photography overhead"),
  },
  {
    slug: "diavola",
    name: "Diavola",
    category: "Pizza",
    price: 649,
    description: "Spicy Italian-style pizza with bold toppings.",
    availability: "both",
    imageQuery: img("italian diavola spicy pizza with chili and salami on wooden board, premium food photography"),
  },
  {
    slug: "quattro_formaggi",
    name: "Quattro Formaggi",
    category: "Pizza",
    price: 699,
    description: "Four-cheese pizza with rich creamy flavor.",
    availability: "both",
    imageQuery: img("italian quattro formaggi four cheese pizza on wooden board, premium food photography"),
  },
  {
    slug: "kebab_di_manzo",
    name: "Kebab di Manzo",
    category: "Pizza",
    price: 699,
    description: "Beef kabab pizza with international fusion flavor.",
    availability: "both",
    imageQuery: img("fusion beef kebab pizza with herbs on wooden board, premium food photography"),
  },
  {
    slug: "pizzaiolo_filippino",
    name: "Pizzaiolo Filippino",
    category: "Pizza",
    price: 749,
    description: "Filipino-style chicken pizza with familiar local flavor.",
    availability: "both",
    imageQuery: img("filipino style chicken pizza with sweet sauce on wooden board, premium food photography"),
  },

  // COFFEE & TEA
  {
    slug: "caffe_americano",
    name: "Caffe Americano",
    category: "Coffee & Tea",
    price: 170,
    description: "Smooth espresso-based black coffee.",
    availability: "both",
    imageQuery: img("americano coffee in ceramic cup on saucer with crema, minimal cafe photography"),
  },
  {
    slug: "caffe_latte",
    name: "Caffe Latte",
    category: "Coffee & Tea",
    price: 190,
    description: "Espresso with steamed milk and creamy foam.",
    availability: "both",
    imageQuery: img("caffe latte with rosetta latte art in ceramic cup, minimal cafe photography"),
  },
  {
    slug: "matcha_latte",
    name: "Matcha Latte",
    category: "Coffee & Tea",
    price: 190,
    description: "Creamy matcha drink with smooth green tea flavor.",
    availability: "both",
    imageQuery: img("matcha latte green tea drink in ceramic cup with foam art, minimal cafe photography"),
  },
  {
    slug: "classic_chai",
    name: "Classic Chai",
    category: "Coffee & Tea",
    price: 220,
    description: "Warm spiced chai tea.",
    availability: "both",
    imageQuery: img("indian classic masala chai in glass cup with cinnamon stick and star anise, premium photography"),
  },

  // FROYO & DESSERTS
  {
    slug: "frozen_yogurt",
    name: "Frozen Yogurt",
    category: "Froyo & Desserts",
    price: 99,
    description: "Creamy frozen yogurt with refreshing flavor.",
    availability: "both",
    imageQuery: img("creamy frozen yogurt swirl in cup with fresh berries, premium dessert photography"),
  },
  {
    slug: "dubai_chocolate_drink",
    name: "Dubai Chocolate Drink",
    category: "Froyo & Desserts",
    price: 220,
    description: "Premium chocolate drink inspired by Dubai chocolate flavors.",
    availability: "both",
    imageQuery: img("dubai chocolate drink with pistachio and kataifi topping in glass, premium drink photography"),
  },
  {
    slug: "dubai_chocolate_kunafa",
    name: "Dubai Chocolate Kunafa",
    category: "Froyo & Desserts",
    price: 899,
    description: "Sweet chocolate kunafa dessert with rich texture.",
    availability: "dine-in",
    imageQuery: img("dubai chocolate kunafa dessert with pistachio drizzle and kataifi, premium dessert photography"),
  },

  // DRINKS
  {
    slug: "italian_soda",
    name: "Italian Soda",
    category: "Drinks",
    price: 170,
    description: "Sparkling flavored soda with refreshing fruity taste.",
    availability: "both",
    imageQuery: img("italian soda in tall glass with strawberry and ice, sparkling pink fruit drink, premium beverage photography"),
  },
  {
    slug: "fruit_juice",
    name: "Fruit Juice",
    category: "Drinks",
    price: 170,
    description: "Refreshing fruit juice selection.",
    availability: "both",
    imageQuery: img("fresh fruit juices selection in tall glasses with citrus and berries, premium beverage photography"),
  },
  {
    slug: "cocktails",
    name: "Cocktails",
    category: "Drinks",
    price: 199,
    description: "Selection of gin, tequila, vodka, rum, brandy, and whiskey-based cocktails.",
    availability: "dine-in",
    imageQuery: img("premium craft cocktails on bar with citrus garnish and ice, moody bar photography"),
  },
  {
    slug: "beers_in_can",
    name: "Beers in Can",
    category: "Drinks",
    price: 120,
    description: "Beer selections including Heineken, Tiger Black, San Mig Light, Pale Pilsen, and Red Horse.",
    availability: "dine-in",
    imageQuery: img("assorted canned beers chilled with condensation on dark wood bar, premium beverage photography"),
  },
]

export const CATEGORIES: ("All" | MenuCategory)[] = [
  "All",
  "Starters",
  "Salads",
  "Royal Platters",
  "Festive Chicken",
  "Shawarma",
  "Western Destinations",
  "Eastern Destinations",
  "Curries",
  "Biryani",
  "Kababs",
  "Pasta",
  "Pizza",
  "Coffee & Tea",
  "Froyo & Desserts",
  "Drinks",
]

export function getMenuItemBySlug(slug: string) {
  return MENU.find((m) => m.slug === slug)
}
